#!/bin/bash

# ***** A simple script to expand a degenerate DNA sequence into all possibilities *******
# Most of this script was generated by Google AI Studio

# Check if an input sequence was provided
if [[ -z "$1" ]]; then
  echo "Usage: $0 <degenerate_sequence>"
  echo "Example: $0 CYGTRCDAAGGTAGCATA TARTYCAACATCGRGGTC out.tsv"
  exit 1
fi

dedegenerate () {
    # Convert the input to uppercase to make the case statement simpler
    degenerate_seq=$(echo "$1" | tr 'a-z' 'A-Z')
    
    # Initialize an array 'sequences' with a single empty string.
    # This is the starting point for building our results.
    sequences=("")
    
    # Loop through each character of the input sequence
    for (( i=0; i<${#degenerate_seq}; i++ )); do
      char="${degenerate_seq:$i:1}"
      
      # This temporary array will hold the new sequences for this iteration
      new_sequences=()
    
      # Define the possible bases for the current character using a case statement
      case "$char" in
        A) expansions=(A) ;;
        C) expansions=(C) ;;
        G) expansions=(G) ;;
        T) expansions=(T) ;;
        R) expansions=(A G) ;; # puRine
        Y) expansions=(C T) ;; # pYrimidine
        S) expansions=(G C) ;; # Strong
        W) expansions=(A T) ;; # Weak
        K) expansions=(G T) ;; # Keto
        M) expansions=(A C) ;; # aMino
        B) expansions=(C G T) ;; # not A
        D) expansions=(A G T) ;; # not C
        H) expansions=(A C T) ;; # not G
        V) expansions=(A C G) ;; # not T
        N) expansions=(A C G T) ;; # aNy
        *)
          echo "Error: Invalid character '$char' found in sequence." >&2
          exit 1
          ;;
      esac
    
      # For each sequence we've already built, append each possible new base
      for seq in "${sequences[@]}"; do
        for base in "${expansions[@]}"; do
          # Add the newly formed sequence to our temporary array
          new_sequences+=("$seq$base")
        done
      done
    
      # Replace the old list of sequences with the new, expanded list
      sequences=("${new_sequences[@]}")
    done
    
    # Print all the final sequences, each on a new lin
    declare -p sequences
}

eval "$(dedegenerate "$1")"
fwd=("${sequences[@]}")
eval "$(dedegenerate "$2")"  
rev=("${sequences[@]}")

#
#declare -a fwd
#declare -a rev
#dedegenerate "$1" fwd
#dedegenerate "$2" rev
:> "$3"
for seq1 in "${fwd[@]}"; do
  # For each element in array1, iterate through each element of array2
  for seq2 in "${rev[@]}"; do
    echo "$seq1 $seq2" >> "$3"
  done
done
