#!/bin/bash
# fix_fasta_headers.sh
# Mostly generated by deepseek

if [ $# -ne 1 ]; then
    echo "Usage: $0 <input.fasta>"
    exit 1
fi

input="$1"
filename=$(basename "$input")
out_dir=$(dirname $PWD/$input)
mkdir -p $out_dir/cleanup
clean_output="$out_dir/${filename%.*}_clean.fasta"
removed_output="$out_dir/cleanup/${filename%.*}_removed.fasta"
logfile="$out_dir/cleanup/${filename%.*}_fix.log"

# manual taxonomy curation: 
# - some headers have errors in fungi
# - some have a comma out of nowhere
# Some unknown species have an sp. XXX at higher levels, we remove those names too
sed -E '
  # Remove commas
  s|,||g;
  # Manual Fix missing kingdoms
  # found using grep "," AML2_WANDA_db_Genus.fa | awk -F";"" "{print $1, $2}"
  # some are arbitrary superior clade names to ensure lower taxonomic level consistency
  s|>Actinopteri|>Metazoa;Chordata;Actinopteri;|g;
  s|>Apicomplexa|>Alveolata;Apicomplexa|g;
  s|>Annelida;|>Metazoa;Annelida;|g;
  s|>Arthropoda;|>Metazoa;Arthropoda;|g;
  s|Actiniaria;Sicyonis|Actiniaria;Sicyonidae;Sicyonis;Sicyonis|g;
  s|>Apicomplexa;|>Alveolata;Apicomplexa;|g;
  s|>Bacillariophyta;|>Ochrophyta;Bacillariophyta;|g;
  s|Bacillati|Bacteria|g;
  s|>Bigyra|>Stramenopiles;Bigyra|g;
  s|>Chordata;|>Metazoa;Chordata;|g;
  s|>Cercozoa;|>Rhizaria;Cercozoa;|g;
  s|>Centroplasthelida;|>Haptista;Centroplasthelida;|g;
  s|>Choanoflagellata;|>Podiata;Holozoa;Choanoflagellata;|g;
  s|>Chordata;|>Metazoa;Chordata;|g;
  s|>Cnidaria;|>Metazoa;Cnidaria;|g;
  s|>Ciliophora;|>Alveolata;Ciliophora;|g;
  s|>Colpodellaceae;|>Alveolata;Chromerida;Colpodellophyceae;Colpodellida;Colpodellaceae;|g;
  s|>Dinophyceae;|>Alveolata;Dinoflagellata;Dinophyceae;|g;
  s|>Evosea;Eumycetozoa;Trichiida;|>Podiata;Amoebozoa;Myxogastria;Trichiida;|g;
  s|>Fungi;Archaeosporales;|>Fungi;Mucoromycota;Glomeromycetes;Archaeosporales;|g;
  s|>Fungi;Paraglomerales;|>Fungi;Mucoromycota;Glomeromycetes;Paraglomerales;|g;
  s|>Glaucocystophyceae;|>Archaeplastida;Glaucophyta;Glaucocystophyceae;|g;
  s|>Haptista;Centroplasthelida;Acanthocystida;|>Chromista;Heliozoa;Centrohelea;Acanthocystida|g;
  s|>Haptista;Centroplasthelida;Meringosphaera;|>Chromista;Ochrophyta;Xanthophyceae;Mischococcales;Pleurochloridaceae;Meringosphaera;|g;
  s|>Haptista;Centroplasthelida;Pseudoraphidiophrys;|>Chromista;Heliozoa;Centrohelea;Centrohelida;Raphidiophryidae;Pseudoraphidiophrys;|g;
  s|>Haptista;Centroplasthelida;Pterocystida;|>Chromista;Heliozoa;Centrohelea;Pterocystida;|g;
  s|>Haptista;Centroplasthelida;Spiculophrys|>Chromista;Heliozoa;Centroplasthelida;Centroplasthelida;Spiculophryidae;Spiculophrys|g;
  s|>Haptista;Centroplasthelida;Yogsothothidae;|>Chromista;Heliozoa;Centroplasthelida;Chthonida;Yogsothothidae;|g;
  s|>Haptophyta;Haptophyta;|>Chromista;Haptophyta;|g;
  s|>Jakobida;|>Protozoa;Loukozoa;Jakobea;Jakobida;|g;
  s|>Preaxostyla;|>Metamonada;Preaxostyla|g;
  s|>Metazoa;Catenulida|>Metazoa;Platyhelminthes;Catenulida|g;
  s|>Metazoa;Clitellata;|>Metazoa;Annelida;Clitellata;|g;
  s|>Metazoa;Metachromadora|>Metazoa;Nematoda;Chromadorea;Desmodorida;Desmodoridae;Metachromadora;|g;
  s|>Mollusca;|>Metazoa;Mollusca;|g;
  s|>Nematoda;|>Metazoa;Nematoda;|g;
  s|Opiliones;Euepedanus;|Opiliones;Epedanidae;Euepedanus;|g;
  s|Opiliones;Icaleptes|Opiliones;Icaleptidae;Icaleptes|g;
  s|Opiliones;Pellobunus;|Opiliones;Samoidae;Pellobunus;|g;
  s|Sclerosomatidae;Leiobunum sp. 1 KTDT-2024a|Sclerosomatidae;Leiobunum;Leiobunum sp. 1 KTDT-2024a|g;
  s|Trombidiformes;Cocceupodes|Trombidiformes;Cocceupodidae;Cocceupodes|g;
  s|Trombidiformes;Mideopsis|Trombidiformes;Mideopsidae;Mideopsis|g;
  s|>Pterocystida;|>Chromista;Heliozoa;Centrohelea;Pterocystida;|g;
  s|>Pterocystis;|>Chromista;Heliozoa;Centrohelea;Pterocystida;Pterocystidae;Pterocystis;|g;
  s|>Rotifera;|>Metazoa;Rotifera;|g;
  s|>Vitrellaceae;|>Alveolata;Chromerida;Colpodellophyceae;Colpodellida;Vitrellaceae;|g;
  
  # Combine fungal taxonomy fixes (order matters!)
  s|Fungi;(Glomerales;Glomeraceae)|Fungi;Mucoromycota;Glomeromycetes;\1|g;
  s|Fungi;(Mucoromycota;)?Glomerales|Fungi;Mucoromycota;Glomeromycetes;Glomerales|g;
  s|Fungi;Glomeromycetes|Fungi;Mucoromycota;Glomeromycetes|g;
  
  # Remove uncultured prefix
  s|uncultured ||g;
  s|uncultured glomeraceous AM fungus||g;
  
  # Replace Glomeromycotina by Glomeromycetes
  s|Fungi;Mucoromycota;Glomeromycotina|Fungi;Mucoromycota;Glomeromycetes|g;
  s|Fungi;Glomeromycotina|Fungi;Mucoromycota;Glomeromycetes|g;
  
  # Remove everything after first space (some species names, we are working at genus lev)
  s| .*||;
  
  # Keep only first 6 semicolon-delimited fields
  s/(([^;]*;){5}[^;]*).*/\1/;
  
  # Remove "fungal" or "fungus" anywhere
  s/fungal|fungus//g
' $input > tmp.fa

input=tmp.fa

> "$clean_output"
> "$removed_output"

echo "Processing $filename..." | tee "$logfile"

# Processing to ensure 6 semicolons regardless of taxa names
awk -v removed="$removed_output" '
BEGIN {
    seq_buffer = ""
    in_removed = 0
}

/^>/ {
    # Process previous sequence if exists
    if (header != "") {
        if (in_removed) {
            # Save removed sequence
            print header "\n" seq_buffer >> removed
        } else {
            # Save cleaned sequence
            print header "\n" seq_buffer
        }
    }
    
    # Reset for new sequence
    header = $0
    seq_buffer = ""
    in_removed = 0
    
    # Count names (non-empty fields between semicolons)
    # First remove leading > and split by ;
    line = substr(header, 2)  # remove >
    n = split(line, fields, ";")
    
    # Count non-empty names
    name_count = 0
    for (i = 1; i <= n; i++) {
        if (fields[i] != "") name_count++
    }
    
    # Remove if fewer than 2 names
    if (name_count < 2) {
        in_removed = 1
        next  # Skip to next record, will be saved in removed file
    }
    
    # Count semicolons in entire header
    sc = gsub(/;/, ";", header)
    
    # Ensure exactly 6 semicolons
    if (sc > 6) {
        # This shouldnt happen normally, but trim to 6 if it does
        # Remove trailing semicolons beyond 6
        while (sc > 6) {
            sub(/;$/, "", header)
            sc--
        }
    } else if (sc < 6) {
        # Add missing semicolons
        while (sc < 6) {
            header = header ";"
            sc++
        }
    }
    next
}

# Sequence lines
{
    if (header == "") next  # safety
    # Append sequence lines, preserving line breaks
    if (seq_buffer == "") {
        seq_buffer = $0
    } else {
        seq_buffer = seq_buffer "\n" $0
    }
}

END {
    # Process last sequence
    if (header != "") {
        if (in_removed) {
            print header "\n" seq_buffer >> removed
        } else {
            print header "\n" seq_buffer
        }
    }
}
' "$input" > "$clean_output"

# Count results
total_headers=$(grep -c '^>' "$input")
clean_headers=$(grep -c '^>' "$clean_output")
removed_headers=$(grep -c '^>' "$removed_output" 2>/dev/null || echo 0)

echo "--- Summary ---" | tee -a "$logfile"
echo "Total headers: $total_headers" | tee -a "$logfile"
echo "Cleaned headers: $clean_headers" | tee -a "$logfile"
echo "Removed headers: $removed_headers" | tee -a "$logfile"

# List some examples of removed sequences
unique_removed_output=$(cat $removed_output | sort -u)
if [ $removed_headers -gt 0 ]; then
    echo -e "\nRemoved headers:" | tee -a "$logfile"
    grep '^>' "$removed_output" | tee -a "$logfile"
fi

# Verify all cleaned headers have 6 semicolons
bad_count=$(grep '^>' "$clean_output" | awk '{if (gsub(/;/, ";", $0) != 6) print}' | wc -l)
if [ $bad_count -eq 0 ]; then
    echo -e "\n✓ All cleaned headers have exactly 6 semicolons." | tee -a "$logfile"
else
    echo -e "\n✗ Warning: $bad_count headers still don't have 6 semicolons!" | tee -a "$logfile"
fi
rm tmp.fa
echo -e "\nOutput files:" | tee -a "$logfile"
echo "Cleaned: $clean_output" | tee -a "$logfile"
echo "Removed: $removed_output" | tee -a "$logfile"
echo "Log: $logfile" | tee -a "$logfile"